apiVersion: v1
kind: Service

metadata:
  name: currency-service
  labels:
    app: currency-app

spec:
  selector:
    app: currency-app

  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000

  type: ClusterIP