apiVersion: v1
kind: Service

metadata:
  name: cart-service
  labels:
    app: cart-app

spec:
  selector:
    app: cart-app

  ports:
    - protocol: TCP
      port: 7070
      targetPort: 7070

  type: ClusterIP