apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config

data:
  CART_SERVICE_ADDR: "cart-service:7070"
  CURRENCY_SERVICE_ADDR: "currency-service:7000"
  SHIPPING_SERVICE_ADDR: "shipping-service:50051"
  PRODUCT_CATALOG_SERVICE_ADDR: "productcatalog-service:3550"
  RECOMMENDATION_SERVICE_ADDR: "recommendation-service:8080"
  AD_SERVICE_ADDR: "ad-service:9555"
  CHECKOUT_SERVICE_ADDR: "checkout-service:5050"