apiVersion: v1
kind: ConfigMap
metadata:
  name: checkout-config

data:
  CART_ADDR: "cart-service:7070"
  CURRENCY_ADDR: "currency-service:7000"
  SHIPPING_ADDR: "shipping-service:50051"
  PRODUCTCATALOG_ADDR: "productcatalog-service:3550"
  EMAIL_ADDR: "email-service:8080"
  PAYMENT_ADDR: "payment-service:50051"